lo-mqtt:
  hostname: liveobjects.orange-business.com
  username: application
  api-key: YOUR_API_KEY
  topics:
    - MESSAGES_TOPIC_1
    - MESSAGES_TOPIC_2
  recovery-interval: 10000
  completion-timeout: 20000
  connection-timeout: 30000
  qos: 1
  keep-alive-interval-seconds: 30  

google:
  pub-sub:
    project-id: YOUR_PROJECT_ID
    topic-id: YOUR_TOPIC_ID
    auth-file: credentials/auth.json
    message-batch-size: 10
    message-sending-fixed-delay: 1000

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics